
name: parse-todays-corona-bz-data

on:
  schedule:
  - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.check.outputs.exists }}

    steps: 
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      
      - name: Check if todays data is already present
        id: check
        run: |
          if [ -f "data/$(date +%Y-%m-%d).json" ]; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
      


  build:
    
    runs-on: ubuntu-latest
    needs: [ check ]
    if: ${{ needs.check.outputs.exists != 'true' }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
          ref: main
        
      - uses: actions/checkout@v3
        with:
          path: gh-pages
          ref: gh-pages

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
        
      - name: Install Dependencies
        run: npm install
        working-directory: ./main
        
      - name: Run Script
        run: npm run run
        working-directory: ./main
        
      - name: Move file to gh-pages and move into gh-pages folder
        run: |
          mkdir -p gh-pages/data
          for file in main/data/*.json; do mv $file gh-pages/data/"${file##*/}"; done 
          rm -rf data
        shell: bash
        working-directory: .
      
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add .
          git commit -m "New Data"
        working-directory: ./gh-pages
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: ./gh-pages

      
